name: sibzamini
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  dio: ^4.0.6 
  carousel_slider: ^4.1.1 
  flutter_svg: ^1.1.6 
  persian_number_utility: ^1.1.2
  rate_in_stars:  ^0.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: 
  json_annotation: ^4.0.1
  geolocator: ^9.0.2
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  lottie: ^2.0.0
  
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.3
  flutter_map: ^0.14.0
  mapir_raster: ^0.0.1
  latlong2: ^0.8.1
  url_launcher: ^6.1.7
  awesome_dialog: ^3.0.2
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_gen_runner: ^5.1.0+1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Regular.ttf
