name: sibzamini
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 
  get:  
  dio:  
  carousel_slider:  
  flutter_svg:  
  persian_number_utility:  
  rate_in_stars:  
  smooth_page_indicator: 
  flutter_rating_bar: 
  # connectivity_plus: 
  # lottie: 
  json_annotation: 
  geolocator: 
  geocoding: 
  shared_preferences: 
  equatable: 
  lottie: 
  connectivity_plus: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  flutter_gen_runner: 
  build_runner: 
  json_serializable: 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Regular.ttf
