const String rSplashScreen = '/';
const String rLoginScreen = '/loginScreen';
const String rSignUpScreen='/signupScreen';
const String rVerifyCodeScreen = '/verifyCodeScreen';
const String rHomeScreen = '/homeScreen';
const String rDetailScreen = '/detailScreen';
const String rLocationScreen = '/locationScreen';
const String rCommentsScreen = '/commentsScreen';
const String rErrorScreen = '/errorScreen';
